// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConversationSubscriptionController from "./conversation_subscription_controller"
application.register("conversation-subscription", ConversationSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ScheduleMeetingController from "./schedule_meeting_controller"
application.register("schedule-meeting", ScheduleMeetingController)
